### ISSUE TITLE
Just added a Spanish version

### ISSUE THREAD

**Issue by rafaecheve** [pragmaticivan/guia-do-trabalho-remoto#1]
Thank you! https://github.com/rafaecheve/guia-de-trabajo-remoto

**Comment by pragmaticivan** [comment]
Nice @rafaecheve , what do you think about create a Pull Request with the file on this repo? On this way turns easy to find and update the file with new informations. ex:    README-es.md

**Comment by rafaecheve** [comment]
sure! that's a great idea!
