### ISSUE TITLE
Empresas que contrata Desenvolvedor Home office

### ISSUE THREAD

**Issue by JGeovani** [pragmaticivan/guia-do-trabalho-remoto#14]
Olá Ivan, blz?

Obrigado por compartilhar seu conhecimento. Alias, você tem uma lista de empresa desenvolvedora que oferecem trabalho de carteira assinada em regime Home Office?

Agradeço,

**Comment by endersonmaia** [comment]
https://github.com/pragmaticivan/guia-do-trabalho-remoto#sites-com-ofertas-remotas

**Comment by JGeovani** [comment]
Olá Enderson, valeu a lista!
Mais interessante é saber quais são as empresas nacionais que oferecem trabalho remoto para desenvolvedor.

**Comment by endersonmaia** [comment]
@JGeovani desse jeito que vc quer, acho difícil existir uma lista, ainda mais atualizada.

Empresas que sei que aceitam trabalho remoto, de cabeça : IBM, Red Hat, AWS, GitHub ...

Todas elas tem em seus próprios sites, uma seção de vagas, e lá vc deve procurar se tem opção de remoto ou não.

O mais comum são sites de empregos que oferecem opção de filtro para vagas remotas, o link que te mandei, alguns são específicos para empregos remotos, outros não. Basta vc procurar palavras chaves como : remote, telecommute, anywhere, global ...

**Comment by pragmaticivan** [comment]
Nacionais provavelmente não existe uma lista, espero criar esta lista nesse projeto.

**Comment by JGeovani** [comment]
Conheci a Zee, que me confirmou contratar para projetos colaboradores home-office. Já experimentei alguma perguntar algumas startups, mas ainda não me confirmaram. Ainda estou buscando mais. 
http://zee.com.br/
