### ISSUE TITLE
Adicionar Artigo como Conteúdo

### ISSUE THREAD

**Issue by djalmaaraujo** [pragmaticivan/guia-do-trabalho-remoto#18]
Gostaria de adicionar meu artigo na lista de conteúdo. Foi bem comentado e muito visualizado, acho que vai ajudar o pessoal.

https://medium.com/desenvolvimento-front-end-pt-br/o-que-eu-aprendi-em-quase-1-ano-de-home-office-7ed3cfee276a

**Comment by djalmaaraujo** [comment]
#19

**Comment by pragmaticivan** [comment]
Merged :dart:
