### ISSUE TITLE
Adaptar front-end para mobile

### ISSUE THREAD

**Issue by pragmaticivan** [pragmaticivan/guia-do-trabalho-remoto#21]

**Comment by cassiocardoso** [comment]
Querem uma ajuda com isso? Posso trabalhar nisso nesse fds.

**Comment by pragmaticivan** [comment]
o/ @cassiocardoso toda ajuda é bem-vinda

**Comment by cassiocardoso** [comment]
Show @pragmaticivan vou dar uma trabalhada nisso então.
