### ISSUE TITLE
Bitwage

### ISSUE THREAD

**Issue by ghost** [pragmaticivan/guia-do-trabalho-remoto#28]
Ouvi falar [desse serviço](https://bitwage.com) hoje. Parece até bom demais para ser verdade. As taxas são pequenas, as opções de distribuição são várias (incluindo BTC e cartão de débito) e o processo é todo transparente ao empregador. Alguém já tem experiência com Bitwage e pode compartilhar?

**Comment by alvesl** [comment]
Parece bem interessante, não conhecia também...
Acabei fazendo um cadastro com eles pra ver como fica. Acredito que a variação que você viu no valor do câmbio foi um pouco "milagroso" - possivelmente devido a um spike no preço do bitcoin. 
mas no geral, se só economizar as taxas do banco ($20 de SWIFT + SPREAD) já compensa..

**Comment by pragmaticivan** [comment]
cc @obetomuniz

**Comment by obetomuniz** [comment]
Fiz todo o processo de Setup como contractor, esse mês ou próximo terei mais feedback sobre o processo inteiro e irei enviar um update pro pessoal aqui. Mas já acrescento que além de tudo, eles também tem suporte no Brasil, que é ótimo por sinal. @alvesl @guilhermeasg @pragmaticivan

**Comment by alvesl** [comment]
Bacana, bom saber @obetomuniz ! Aguardamos seu feedback. Eu também fiz o processo como contractor e vou testar assim que a documentação for aprovada - também darei meu feedback por aqui!

**Comment by janjitsu** [comment]
@obetomuniz estou fazendo o setup lá, não ficou muito claro para mim qual o suporte que eles dão pro Brasil, como funciona?

**Comment by ghost** [comment]
Eu fiz o cadastro semana passada, eles prometeram resposta em dois dias
úteis e até agora nada. ;(

2016-06-24 17:16 GMT-03:00 Guilherme Augusto guilhermea@outlook.com.br:

**Comment by janjitsu** [comment]
@guilhermeasg no email eles falam que se demorar mais de 2 dias que entre em contato, vc tentou isso?

**Comment by obetomuniz** [comment]
@janfrs no caso em PT-BR, é só ir no chat deles mesmo e perguntar sobre suporte em Português, dai eles vão te orientar direitinho.
@guilhermeasg no meu caso demorei 3 dias, todo o processo.

**Comment by ghost** [comment]
- Nenhum endereço de e-mail pra contato
- O form de suporte no site não envia mensagem (server retorna erro 500 e o cliente fica _"loading"_ forever)
- Chat online não funciona
- Cliente Android diz que o meu e-mail é inválido, mas eu uso ele normalmente na web
- Remote Ok

**Dica:** essa galera tá precisando urgente de um gerente de produto

**Comment by janjitsu** [comment]
@guilhermeasg que merda... tive meu cadastro aprovado sem broncas. Mas se for realmente assim impossível de reclamar, fico com um pé atrás...

**Comment by ghost** [comment]
@janfrs já não estou mais tão extático com a empresa quanto estive antes, hahah. Mas pedi suporte pelo Twitter como última tentativa, mantenho-lhes informados.

**Comment by janjitsu** [comment]
@guilhermeasg tive um problema também e mandei um email e recebi resposta na hora, o contato é fabiano dias skype: biano.dias tenta falar com ele

**Comment by obetomuniz** [comment]
Pois é @janfrs também conversei com ele, ainda não disse nada aqui pois ainda estou aguardando concluir o processo de ponta a ponta, mas de fato não tive nenhum problema (que eu mesmo não tenha causado). E sobre o form @guilhermeasg no site deles, funcionou perfeitamente comigo, não foi imediata a resposta, mas recebi feedback no meu email em poucas horas. Isso é normal quando o chat é usado em modo offline.

**Comment by ghost** [comment]
Valeu @janfrs e @obetomuniz, mandei e-mail e eles resolveram, minha conta foi finalmente aprovada! Tenho um _invoice_ pra enviar amanhã, mas agora fiquei com o pé um pouco atrás de fazer isso com eles... acho que vou esperar o @obetomuniz contar pra gente como foi. ;)

**Comment by janjitsu** [comment]
@guilhermeasg vou mandar uma invoice por esses dias também, o biano.dias me recomendou transferir o pagamento através do www.foxbit.com.br, fiquei muito interessado. Eles estão em parceria com a bitwage.

**Comment by ghost** [comment]
@janfrs eu tenho conta no Coinbase e só agora fui me dar conta de que eles não transferem pra minha conta do banco. Dei uma pesquisada aqui e não encontrei nada, que tipo de parceria é essa?

Parece que o Foxbit usa um endereço diferente pra cada depósito (consequentemente, um endereço por _invoice_), é isso mesmo?

**Comment by janjitsu** [comment]
@guilhermeasg é isso mesmo, cada vez que você vai mandar bitcoins para sua conta na foxbit, ele gera um endereço bitcoin diferente, o propósito da foxbit é ser apenas uma exchange, não é exatamente uma carteira bitcoin. Porem o biano.dias me falou que no caso do bitwage este endereço continua válido para várias transações, fruto da parceria entre eles, irei testar se é assim mesmo. Outra idéia é criar uma carteira na uphold, ou coinbase e manter os bitcoins lá, e quando for necessário fazer saques, transferir para o foxbit.

Obs: https://www.youtube.com/watch?v=Q5OqwmuGUzY

**Comment by alvesl** [comment]
Fala galera!
Realizei o cadastro na bitwage, porém ainda não enviei nenhum invoice (só mês que vem que conseguirei testar)..
resumindo o que sei até agora:
- Conversei com a staff da bitwage e parece que os brasileiros estão transferindo os bitcoins pra uma carteira própria (para um endereço seu mesmo), e depois negociando ou na FoxBit ou na Mercado, conforme a melhor cotação..
  Isso pode dar um pouquinho mais de trabalho, mas aparentemente as taxas ficam melhores e vc não tem esse problema do endereço mudar.

Quando tiver mais informações mando um update.. abs

**Comment by pragmaticivan** [comment]
Aew! Vlw @obetomuniz  https://github.com/nomadsonrails/guia-do-trabalho-remoto/pull/29

**Comment by janjitsu** [comment]
Recebi um payroll através do bitwage, o valor foi convertido em bitcoin e enviado para a carteira do foxbit, sucesso! acho q podemos fechar a issue

**Comment by pragmaticivan** [comment]
Show!
