### ISSUE TITLE
site down?

### ISSUE THREAD

**Issue by caarlos0** [pragmaticivan/guia-do-trabalho-remoto#61]
https://guiadotrabalhoremoto.com parece fora pra mim... :(

**Comment by pragmaticivan** [comment]
;/ domain foi pro limbo. To vendo outra forma de fazer hosting disso sem pagar domain.

**Comment by pragmaticivan** [comment]
Atualizado pra subdomain temporário, vlw! https://guia-do-trabalho-remoto.netlify.com/
